### ISSUE TITLE
replace github.com/NebulousLabs/entropy-mnemonics" with bip-0039

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/rivine#116]
a more generally known spec and wordlist since it then has reviewed implementations in different languages
suggest to use trezor wordlist
https://github.com/trezor/python-mnemonic
go implementations exist  like https://github.com/tyler-smith/go-bip39

**Comment by GlenDC** [comment]
@lafont-e we forked the go-bip39 lib. You can find it at https://github.com/rivine/go-bip39

Please use that fork instead of `github.com/NebulousLabs/entropy-mnemonics`. Meaning you will delete the vendored `github.com/NebulousLabs/entropy-mnemonics`, and vendor (using `dep`) `https://github.com/rivine/go-bip39` at latest master.

You will also have to adapt the rivine code to use the new API, as exposed by `rivine/go-bip39`. It's OK this is a new API, we do not care about having to change the code everywhere `NebulousLabs/entropy-mnemonics` was used. There is no desire to keep compatibility with the `NebulousLabs/entropy-mnemonics` API, and instead wish to use the `rivine/go-bip39` API as it is.

**Comment by GlenDC** [comment]
closed by 94bea4a
