### ISSUE TITLE
checkRevertApply fail

### ISSUE THREAD

**Issue by nvinken** [rivine/rivine#28]
In debug mode, there is an extra check that is sometimes done at random. One of the checks is checkRevertApply. 

checkRevertApply reverts the most recent block, checking to see that the consensus set hash matches the hash obtained for the previous block. Then it applies the block again and checks that the consensus set hash matches the original consensus set hash. 

The check with the parent failes because the 10 maturitydelayed coin fee transactions are not good synced for this check. (there is an offset of 1 transaction):

When printing: 
```
		fmt.Println("->")
		// The bucket is a prefixed bucket - add all elements to the tree.
		return b.ForEach(func(k, v []byte) error {
			fmt.Println("k ", k, " v ", v)
			tree.Push(k)
			tree.Push(v)
			return nil
		})
```
->
k  [197 166 251 209 127 249 153 226 222 131 244 165 6 230 150 162 179 112 147 52 43 193 81 192 129 57 163 254 166 180 152 6]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [81 80 17 220 49 137 153 24 40 7 12 79 15 35 191 170 130 24 67 252 186 189 89 250 44 60 13 239 228 168 151 68]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [117 181 39 238 56 145 227 53 150 156 19 102 126 215 134 127 189 74 132 185 199 84 127 233 37 88 51 236 37 105 51 161]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [24 201 235 127 55 254 48 99 93 159 80 161 255 183 255 244 118 92 227 226 135 124 2 79 22 77 254 203 194 51 235 72]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [43 42 117 204 97 152 161 39 87 37 206 144 88 170 52 11 167 118 181 58 156 208 130 78 100 78 161 0 102 143 126 153]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [102 129 110 31 51 82 114 168 249 145 203 177 181 24 161 186 125 46 23 151 70 209 194 245 173 197 52 24 215 166 28 250]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [237 149 27 226 233 38 74 104 169 31 72 51 36 214 0 78 249 136 79 182 75 108 69 181 97 137 191 254 34 184 50 132]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [72 229 32 237 163 158 96 53 236 197 28 98 93 9 240 189 235 46 15 32 191 1 201 8 68 54 106 74 72 22 33 47]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [82 72 101 171 192 252 180 88 15 50 90 195 10 62 231 0 4 243 30 175 27 9 112 154 94 40 141 30 189 148 142 118]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [196 182 240 166 40 166 46 150 235 104 150 65 19 17 118 45 48 219 40 15 48 78 159 116 201 198 124 64 88 250 20 148]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
tree.Root()  e72e80083ba5907420dad383d48661d3d5d305df6bb2b8a527f93422974f4082

->
k  [41 219 173 109 136 193 51 99 17 112 91 232 220 74 184 87 159 52 245 188 210 241 81 71 68 45 165 210 246 131 184 152]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [197 166 251 209 127 249 153 226 222 131 244 165 6 230 150 162 179 112 147 52 43 193 81 192 129 57 163 254 166 180 152 6]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [81 80 17 220 49 137 153 24 40 7 12 79 15 35 191 170 130 24 67 252 186 189 89 250 44 60 13 239 228 168 151 68]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [117 181 39 238 56 145 227 53 150 156 19 102 126 215 134 127 189 74 132 185 199 84 127 233 37 88 51 236 37 105 51 161]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [24 201 235 127 55 254 48 99 93 159 80 161 255 183 255 244 118 92 227 226 135 124 2 79 22 77 254 203 194 51 235 72]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [43 42 117 204 97 152 161 39 87 37 206 144 88 170 52 11 167 118 181 58 156 208 130 78 100 78 161 0 102 143 126 153]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [102 129 110 31 51 82 114 168 249 145 203 177 181 24 161 186 125 46 23 151 70 209 194 245 173 197 52 24 215 166 28 250]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [237 149 27 226 233 38 74 104 169 31 72 51 36 214 0 78 249 136 79 182 75 108 69 181 97 137 191 254 34 184 50 132]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [72 229 32 237 163 158 96 53 236 197 28 98 93 9 240 189 235 46 15 32 191 1 201 8 68 54 106 74 72 22 33 47]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
->
k  [82 72 101 171 192 252 180 88 15 50 90 195 10 62 231 0 4 243 30 175 27 9 112 154 94 40 141 30 189 148 142 118]  v  [11 0 0 0 0 0 0 0 82 183 210 220 200 12 210 228 0 0 0 230 107 190 150 56 174 14 153 134 65 220 159 170 1 128 193 90 16 113 177 118 119 132 205 218 17 173 60 29 48 159 166]
tree.Root()  1132f47fe8072ede9c642ee0d13b9560650e57a42221108b9fcec75765d93c96

**Comment by lafont-e** [comment]
I'm reviewing this issue and I need a little help, I don't understand fully the code.

From what I see, the checksum is a merkle tree of all records in buckets BlockPath, CoinOutputs, BlockStakeOutputs, and buckets prefixed dco_ and fcex_. 

The comparison is done between the checksum at the time the parent  block was added and the  parent block as it is now, but don't understand why the parent is forked from the consensus as the parent is already in the consensus.

I understand that CoinOutputs may have changed, as current block has been processed but the fork only reverts blocks, nothing more, so CoinOutputs does not seem to reflect the changes done forking the consensus as the block spending may not be equal between parent and current. Same for BlockStakeOutputs.

Should it be a possible solution to revert Coins and BlockStake to its original position before doing the consensuschecksum ?

Or, as doing a consensuschecksum now is a very costly operation (reading all records from at least 3 buckets) calculated for every new block added  and sometimes  (every 1000 blocks randomly) and it will be costlier when this thing is 20 years running, maybe we should think on another cheaper way to guarantee to consistency of the consensus 

Also the consensusChecksum can be changed for a checking of only BlockPath, as from what I understand, CoinOutputs and BlockStakeOutputs are derived from the blocks on BlockPath and verifiable just reading the BlockPath.

Not sure everything I've wrote make any sense, but any light about this that may help me solve this issue is greatly appreciated.

**Comment by LeeSmet** [comment]
Still present. The problem is that whenever a block is applied, there is also some "maintenance". This is mainly the addition of the delayed outputs to the consensus set, and removing the delayed bucket. But when the block is reverted, there seems to be no such action which restores the delayed bucket. As a result, the consensus set id (which also takes the values from these buckets) is wrong
