### ISSUE TITLE
Transactions are not propagated when a new node comes online

### ISSUE THREAD

**Issue by LeeSmet** [rivine/rivine#286]
It seems that a transaction is only relayed by the transactionpool when this pool receives it. Because of this its possible that a transaction which is created before blockcreators are online will indefinitely stay in the pool as no block creators will include it in a block.

**Comment by GlenDC** [comment]
I propose that we add a new RPC (or pair of RPCs) as to allow peers to exchange transactions from their transaction pool. Such that no matter when you connect, your transaction pool is up to date with the network.

Some details will still have to be worked out. For example, which transactions to remove when the result of the exchange is too many transactions in the pool?

**Comment by LeeSmet** [comment]
A new RPC to accomplish this is certainly required. that being said, we should take into account that it only makes sense to call this RPC when the daemon is done with syncing (as otherwise the transactionpool set might not be valid). Once the syncing is done, we can update the transactionpool set by requesting the full set from the connected nodes. Like the IBD, it might be best to prioritize peers on outbound connections. Regardless, we probably want to pull some kind of hash first from all these nodes so we have some form of consensus regarding the transaction set to add as well I feel

**Comment by LeeSmet** [comment]
Given the problems with syncing the trasnactionpool, the best approach might be to just broadcast the txn again every few blocks for a while, as discussed with @robvanmieghem .

**Comment by LeeSmet** [comment]
@GlenDC please elaborate

**Comment by GlenDC** [comment]
> we probably want to pull some kind of hash first

Not sure if this is required, we don't do this now either. The only thing it shares is raw transactions, which have to be valid and cannot exist yet (no duplicate txs allowed). I think as long as both are true, I do not see what can go wrong.

> Given the problems with syncing the transactionpool

I don't see how this new RPC would make that different from what we now do. When you are a connected node you do already receive new transactions from other nodes even when you are still syncing. So what would make the difference that you also receive a bunch of txs right at the point that you establish a connection with another txpool-enabled node?

There is no danger, 3 things can happen for each received tx:

* the tx is invalid: it gets rejected;
* the tx is a duplicate (as in it already exists): it gets rejected (this can also happen if that other node is not as far synced as we are);
* the tx is valid and doesn't exist yet: it gets accepted (should we not be synced yet, it must mean that that other node wasn't synced yet either. If so, no problem, because our consensus will catch up and mark that tx as created, removing it from our pools, so all good in that situation as well);

**Comment by robvanmieghem** [comment]
Why would this be such a bad idea? It would put the responsibility to the broadcasting daemon that might be disconnected  or badly connected at the time of broadcast. A badly connected client might also be one that is connected to older peers that do not accept a new tx version yet or a temporary split  of the network.This is especially true for explorers serving light clients.
It would also solve the problem of a full transactionpool in case someone is spoofing the network.
