### ISSUE TITLE
Atomic swap claims fails

### ISSUE THREAD

**Issue by LeeSmet** [rivine/rivine#318]
Output lock does not seem to work for V1 txns

**Comment by GlenDC** [comment]
The problem that motivated the creation of this issue, also hid another problem. So Let me recap the 2 problems and how they are fixed in 87d62ff.

Working on this issue, as well as the quick-development process of the TF App Team on their wallet (as to prepare for the 1.0.5 release) also proved the value of pair programming, both for difficult problems as well as when it really has to go quick.

## problem 1

When claiming/refunding an atomic swap tool using the client CLI tool, we allow you to specify just partial information, such that we get the rest of the information from an explorer node. However in that case we didn't create a condition yet, making that unlock hash being nil by default. This is now fixed, by ensuring that if we can and have to, we create that condition for the user, based on our already fetched explorer info for that outputID (hash). Fixing problem 1.

## problem 2

Fixing problem 1, showed another previously unknown bug. In our daemon types module, we have a private type `anyAtomicSwapFulfillment`. This is a private hidden structure created for the purpose of being able to decode an atomic swap fulfillment both in the new as well as the old format. The problem was however that after adding and using this type, we forgot to add support for it to the AtomicSwapCondition and UnlockHashCondition Fulfill logic, making it not recognize that type. Adding support for it fixed this problem as well, which is confirmed by adding unit test cases as well as a quick manual test, showing that now we can indeed do a claim using the command line tool, once again.
