### ISSUE TITLE
The atomic swap claim command requires the explorer module

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/rivine#346]
```
$tfchainc  atomicswap claim 8e4384762e4b3add0ec9416d14a4bc10c8477fb088fb933663c38ed9e3a6fcd9 d44b02204617e4744d6d4d3ccab7e89c398adaed879c5b 123
Could not get blockStake/coin output from explorer: API call not recognized: /explorer/hashes/8e4384762e4b3add0ec9416d14a4bc10c8477fb088fb933663c38ed9e3a6fcd9
```
at testnet ( almost no transactions)at  height 35337, enabling the explorer module:
`Finished loading in 1151.350558224 seconds`

**Comment by GlenDC** [comment]
It does not require the explorer, the requirement of the explorer module is optional.

It can do everything automatically, if you give all info yourself. Hence why the signature is

```
rivinec atomicswap claim outputid secret [dest src timelock hashedsecret] amount [flags]
```

In the above command, you'll have to give `dest src timelock hashedsecret` as well, in order to avoid the need for the explorer.
