### ISSUE TITLE
explorer module doesn't always find spending transactions for (unlock) hash

### ISSUE THREAD

**Issue by LeeSmet** [rivine/rivine#407]

**Comment by LeeSmet** [comment]
example: https://explorer.testnet.threefoldtoken.com/hash.html?hash=01a8e6c27bd5461d27745ec7ae870b2e47a9c62f14218f1ec09f7b6824fa82c9937af9255adf79

**Comment by LeeSmet** [comment]
It seems like the spending transaction is not found when looking for the unlock hash in the explorer db

**Comment by GlenDC** [comment]
Fairly certain because lines such as https://github.com/rivine/rivine/blob/1f74883f7ed136156f668df96f5b1d40ef0de2a5/modules/explorer/update.go#L66, https://github.com/rivine/rivine/blob/1f74883f7ed136156f668df96f5b1d40ef0de2a5/modules/explorer/update.go#L137 and more, check on `err != nil`, while it should be `err == nil`.
